### ISSUE TITLE
Controls not writing value to form object when manually input.

### ISSUE THREAD

**Issue by Raphilass** [eswarpr/ng-fabric#1]
The form controls are now updating the form object only via NgModel and not by user input.  For example.

I have a simple form, 1 text box and 1 button with a div showing the output for form.value

```
<form #form="ngForm">     
          <div>
            <fabric-text-field #txtbox label="enter name" [(ngModel)]="_name" name="_name"></fabric-text-field>
          </div>
          <div>
            <fabric-primary-button (onClick)="_handleSubmitForm()" text="Submit"
              style="display: inline-block;margin-right: 15px;"></fabric-primary-button>
          </div>
        </form>
        <div>
          {{form.value | json}}
        </div>
```

The _handleSubmitForm() event simply sets the _name property to a fixed string.

`_handleSubmitForm(f:NgForm){
    console.log("changing text");
    this._name = "I have changed"
  }`

**Behaviour**

1. Type into the form, the form object is not updated so the JSON object written out beneath the form remains empty.
2. Click the button and update the model programatically, the JSON object is also updated.

**Expected Behaviour**

1. Type into the form, the form object WILL be updated so the JSON object written out beneath the form remains shows the Key Value Pair for that control.
2. Click the button and update the model programatically, the JSON object is also updated, currently correct.

**Comment by eswarpr** [comment]
I could not replicate this issue. Could you setup a [plunker](https://next.plnkr.co/) for this please, and post it here?

**Comment by eswarpr** [comment]
Looks like a merge issue with upstream. Closing for now
